### ISSUE TITLE
マイリストが全て未視聴状態のままになる。

### ISSUE THREAD

**Issue by bmg0083dark** [nndd-reboot/NNDD#14]
NNDDスレに書き込めないのでこちらに報告
再生しようが、右クリックで視聴済みにしようが
未視聴状態のままです。
解除されません。
nfindeは以下の対策がされ、マイリストで最新作確認が出来るようになりました。
https://writening.net/page?PLBX4K

**Comment by luftwaffe1975** [comment]
また同じ状態になってますね

**Comment by bmg0083dark** [comment]
今回は、sm20万番台のファイルのリストだと視聴済みに設定すらできなくなっています。
最近のsm40万番台のファイルは視聴済みにできるため気が付いていないのかもしれません。
さらに、マイリストが強調されてなくても未視聴状態のままで変更できない状態です。
5chは浪人購入しない限りほぼ書き込めないのでここで報告します。

**Comment by nndd-reboot** [comment]
現状のマイリスのURLは正確には`mylist/12345`ではなく`user/12345/mylist/12345`であって`mylist/12345`にアクセスした場合はリダイレクトされます。
現象としてはマイリスを読み込むはずがユーザの動画一覧を読み込む動作をしてしまっているのでおそらくアクセス対象の問題。
前回とは症状自体が別物に思えます。

**Comment by nndd-reboot** [comment]
おそらくマイリスが`mylist/12345`から`user/12345/mylist/12345`になったことによりユーザ投稿動画一覧として判定されてしまうことによりマイリスのデータが取得できなくなっている。
