### ISSUE TITLE
マイリストで動画一覧からの取得した時の動画数がおかしい

### ISSUE THREAD

**Issue by inuyoshizawa** [nndd-reboot/NNDD#15]
投稿者ページの動画・シリーズの動画一覧(user/video)からマイリスト登録していたリストの動画数が本来の投稿数の2倍～10倍くらいに膨れあがってしまっています。
どうやら同じ動画がリストの中に複数存在しているみたいですし、未視聴状態のまま解除もできません。
正常な登録数の投稿者もありますが登録したリストの大半がこのような状態になってます。

**Comment by nndd-reboot** [comment]
ニコニコのRSSがバグってる。
1ページ目は1件目から30個、2ページ目は31件目から60個、3ページ目は61件目から90個取れる。
今さら直さないだろうから独自に対応する必要がある。
